#lang errortrace racket/base

(require "environment.rkt"
         "bitcoin-environment.rkt"
         "eval-script.rkt"
         "../transaction.rkt"
         "../../crypto-utils.rkt")

(module+ test
  (require rackunit))


(module+ test
  (test-case
      "smoke test for making bitcoin environment"
    (let ([bitcoin-env (make-bitcoin-environment)])
      (check-not-eq? bitcoin-env '())
      (check-true (is-opcode? #x00 bitcoin-env))
      (check-true (is-opcode? #x01 bitcoin-env))
      )))

(module+ test
  (test-case
      "test bitcoin opcodes in bitcoin-environment"
    (let ([bitcoin-env (make-bitcoin-environment)])
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_false '() bitcoin-env '() '() '())])
        (check-equal? stack `(,zero)))
      (let-values ([(script stack altstack condstack verified) (apply-opcode #x01 '(#"A") bitcoin-env '() '() '())])
        (check-equal? script '())
        (check-equal? stack  '(#"A")))
      (let-values ([(script stack altstack condstack verified) (apply-opcode #x02 '(#"BC") bitcoin-env '() '() '())])
        (check-equal? script '())
        (check-equal? stack  '(#"BC")))
      (let-values ([(script stack altstack condstack verified) (apply-opcode #x4c '(#x02 #"BC") bitcoin-env '() '() '())])
        (check-equal? script '())
        (check-equal? stack '(#"BC")))
      (let-values ([(script stack altstack condstack verified) (apply-opcode #x4d '(#x0002 #"BC") bitcoin-env '() '() '())])
        (check-equal? script '())
        (check-equal? stack '(#"BC")))
      (let-values ([(script stack altstack condstack verified) (apply-opcode #x4e '(#x000002 #"BC") bitcoin-env '() '() '())])
        (check-equal? script '())
        (check-equal? stack '(#"BC")))
      (let-values ([(script stack altstack condstack verified) (apply-opcode #x4f '() bitcoin-env '(blah) '() '())])
        (check-equal? script '())
        (check-equal? stack '(-1 blah)))
      (let-values ([(script stack altstack condstack verified) (apply-opcode #x51 '() bitcoin-env '(blah) '() '())])
        (check-equal? script '())
        (check-equal? stack '(1 blah)))
      (let-values ([(script stack altstack condstack verified) (apply-opcode #x52 '() bitcoin-env '(blah) '() '())])
        (check-equal? script '())
        (check-equal? stack '(2 blah)))
      (let-values ([(script stack altstack condstack verified) (apply-opcode #x60 '() bitcoin-env '(blah) '() '())])
        (check-equal? script '())
        (check-equal? stack '(16 blah)))
      (let-values ([(script stack altstack condstack verified) (apply-opcode #x61 '() bitcoin-env '(blah) '() '())])
        (check-equal? script '())
        (check-equal? stack '(blah)))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_if '(#x4c 2 #"AA" #x4c 3 #"AAA" op_endif) bitcoin-env '(1 blah) '() '())])
        (check-equal? script '(#x4c 2 #"AA" #x4c 3 #"AAA" op_endif))
        (check-equal? stack '(blah))
        (check-equal? condstack '(1)))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_if '(#x4c 2 #"AA" #x4c 3  #"AAA" op_endif) bitcoin-env `(,zero blah) '() '())])
        (check-equal? script '(#x4c 2 #"AA" #x4c 3  #"AAA" op_endif))
        (check-equal? stack '(blah))
        (check-equal? condstack '(0)))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_if '(#x4c 2 #"AA" #x4c 3  #"AAA" op_else #x4c 2 #"BB" #x4c 3  #"BBB" op_endif) bitcoin-env '(1 blah) '() '())])
        (check-equal? script '(#x4c 2 #"AA" #x4c 3  #"AAA" op_else #x4c 2 #"BB" #x4c 3  #"BBB" op_endif))
        (check-equal? stack '(blah))
        (check-equal? condstack '(1)))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_if '(#x4c 2 #"AA" #x4c 3  #"AAA" op_else #x4c 2 #"BB" #x4c 3  #"BBB" op_endif) bitcoin-env `(,zero blah) '() '())])
        (check-equal? script '(#x4c 2 #"AA" #x4c 3  #"AAA" op_else #x4c 2 #"BB" #x4c 3  #"BBB" op_endif))
        (check-equal? stack '(blah))
        (check-equal? condstack '(0)))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_notif '(#x4c 2 #"AA" #x4c 3  #"AAA" op_endif) bitcoin-env `(,zero blah) '() '())])
        (check-equal? script '(#x4c 2 #"AA" #x4c 3  #"AAA" op_endif))
        (check-equal? stack '(blah))
        (check-equal? condstack '(1)))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_notif '(#x4c 2 #"AA" #x4c 3  #"AAA" op_endif) bitcoin-env '(1 blah) '() '())])
        (check-equal? script '(#x4c 2 #"AA" #x4c 3  #"AAA" op_endif))
        (check-equal? stack '(blah))
        (check-equal? condstack '(0)))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_notif '(#x4c 2 #"AA" #x4c 3  #"AAA" op_else #x4c 2 #"BB" #x4c 3  #"BBB" op_endif) bitcoin-env `(,zero blah) '() '())])
        (check-equal? script '(#x4c 2 #"AA" #x4c 3  #"AAA" op_else #x4c 2 #"BB" #x4c 3  #"BBB" op_endif))
        (check-equal? stack '(blah))
        (check-equal? condstack '(1)))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_notif '(#x4c 2 #"AA" #x4c 3  #"AAA" op_else #x4c 2 #"BB" #x4c 3  #"BBB" op_endif) bitcoin-env '(1 blah) '() '())])
        (check-equal? script '(#x4c 2 #"AA" #x4c 3  #"AAA" op_else #x4c 2 #"BB" #x4c 3  #"BBB" op_endif))
        (check-equal? stack '(blah))
        (check-equal? condstack '(0)))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_if '(op_if #x4c 2 #"ZZ" op_endif op_else #x4c 2 #"BB" #x4c 3  #"BBB" op_endif) bitcoin-env '(1 1 blah) '() '())])
        (check-equal? script '(op_if #x4c 2 #"ZZ" op_endif op_else #x4c 2 #"BB" #x4c 3  #"BBB" op_endif))
        (check-equal? stack '(1 blah))
        (check-equal? condstack '(1)))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_verify '() bitcoin-env `(,zero) '() '())])
          (check-equal? verified #f))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_return '(#"AAA" #"BBB") bitcoin-env `(,zero) '() '())])
        (check-equal? stack `(,zero))
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #f))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_toaltstack '(#"AAA" #"BBB") bitcoin-env `(,zero) '() '())])
        (check-equal? stack '())
        (check-equal? altstack `(,zero))
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_fromaltstack '(#"AAA" #"BBB") bitcoin-env `(,zero) '(1) '())])
        (check-equal? stack `(1 ,zero))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_ifdup '(#"AAA" #"BBB") bitcoin-env '(1) '() '())])
        (check-equal? stack '(1 1))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_ifdup '(#"AAA" #"BBB") bitcoin-env `(,zero 1) '() '())])
        (check-equal? stack `(,zero 1))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_depth '(#"AAA" #"BBB") bitcoin-env `(,zero 1) '() '())])
        (check-equal? stack `(2 ,zero 1))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_drop '(#"AAA" #"BBB") bitcoin-env `(,zero 1) '() '())])
        (check-equal? stack '(1))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_drop '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_dup '(#"AAA" #"BBB") bitcoin-env `(,zero 1) '() '())])
        (check-equal? stack `(,zero ,zero 1))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_dup '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_nip '(#"AAA" #"BBB") bitcoin-env `(,zero 1) '() '())])
        (check-equal? stack `(,zero))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_nip '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_over '(#"AAA" #"BBB") bitcoin-env `(,zero 1 2 3) '() '())])
        (check-equal? stack `(1 ,zero 2 3))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_over '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_pick '(#"AAA" #"BBB") bitcoin-env '(3 a b c d) '() '())])
        (check-equal? stack '(d a b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_pick '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_roll '(#"AAA" #"BBB") bitcoin-env '(2 a b c d) '() '())])
        (check-equal? stack '(c a b d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_roll '(#"AAA" #"BBB") bitcoin-env `(,zero a b c d) '() '())])
        (check-equal? stack '(a b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_roll '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_rot '(#"AAA" #"BBB") bitcoin-env '(a b c d) '() '())])
        (check-equal? stack '(d a b c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_rot '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_swap '(#"AAA" #"BBB") bitcoin-env '(a b c d) '() '())])
        (check-equal? stack '(b a c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_swap '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_tuck '(#"AAA" #"BBB") bitcoin-env '(a b c d) '() '())])
        (check-equal? stack '(a b a c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_tuck '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_2drop '(#"AAA" #"BBB") bitcoin-env '(a b c d) '() '())])
        (check-equal? stack '(c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_2drop '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_2dup '(#"AAA" #"BBB") bitcoin-env '(a b c d) '() '())])
        (check-equal? stack '(a b a b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_2dup '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_3dup '(#"AAA" #"BBB") bitcoin-env '(a b c d) '() '())])
        (check-equal? stack '(a b c a b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_3dup '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_2over '(#"AAA" #"BBB") bitcoin-env '(a b c d) '() '())])
        (check-equal? stack '(c d a b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_2over '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_2rot '(#"AAA" #"BBB") bitcoin-env '(a b c d e f g h) '() '())])
        (check-equal? stack '(e f a b c d g h))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_2rot '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_2swap '(#"AAA" #"BBB") bitcoin-env '(a b c d e f g h) '() '())])
        (check-equal? stack '(c d a b e f g h))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_2swap '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_size '(#"AAA" #"BBB") bitcoin-env '("abcd" x) '() '())])
        (check-equal? stack '(4 "abcd" x))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_size '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_equal '(#"AAA" #"BBB") bitcoin-env '(a a b c d) '() '())])
        (check-equal? stack '(#t b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_equal '(#"AAA" #"BBB") bitcoin-env '(a e b c d) '() '())])
        (check-equal? stack '(#f b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_equal '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_equalverify '(#"AAA" #"BBB") bitcoin-env '(a a b c d) '() '())])
        (check-equal? stack '(b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_equalverify '(#"AAA" #"BBB") bitcoin-env '(a e b c d) '() '())])
        (check-equal? stack '(b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #f))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_equalverify '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #f))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_1add '(#"AAA" #"BBB") bitcoin-env '(10 100) '() '())])
        (check-equal? stack '(11 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_1add '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_1sub '(#"AAA" #"BBB") bitcoin-env '(10 100) '() '())])
        (check-equal? stack '(9 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_1sub '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_negate '(#"AAA" #"BBB") bitcoin-env '(10 100) '() '())])
        (check-equal? stack '(-10 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_negate '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_abs '(#"AAA" #"BBB") bitcoin-env '(-10 100) '() '())])
        (check-equal? stack '(10 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_abs '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_not '(#"AAA" #"BBB") bitcoin-env `(,zero 100) '() '())])
        (check-equal? stack '(1 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_not '(#"AAA" #"BBB") bitcoin-env '(1 100) '() '())])
        (check-equal? stack `(,zero 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_not '(#"AAA" #"BBB") bitcoin-env '(a 100) '() '())])
        (check-equal? stack `(,zero 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_not '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_0notequal '(#"AAA" #"BBB") bitcoin-env `(,zero 100) '() '())])
        (check-equal? stack `(,zero 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_0notequal '(#"AAA" #"BBB") bitcoin-env '(1 100) '() '())])
        (check-equal? stack '(1 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_0notequal '(#"AAA" #"BBB") bitcoin-env '(a 100) '() '())])
        (check-equal? stack '(1 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_0notequal '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_add '(#"AAA" #"BBB") bitcoin-env '(1 100) '() '())])
        (check-equal? stack '(101))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_add '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_sub '(#"AAA" #"BBB") bitcoin-env '(100 10) '() '())])
        (check-equal? stack '(90))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_sub '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_booland '(#"AAA" #"BBB") bitcoin-env '(a b c) '() '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_booland '(#"AAA" #"BBB") bitcoin-env `(,zero ,zero c) '() '())])
        (check-equal? stack `(,zero c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_booland '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_boolor '(#"AAA" #"BBB") bitcoin-env `(a ,zero c) '() '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_boolor '(#"AAA" #"BBB") bitcoin-env `(,zero ,zero c) '() '())])
        (check-equal? stack `(,zero c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_boolor '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_numequal '(#"AAA" #"BBB") bitcoin-env '(10 10 c) '() '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_numequal '(#"AAA" #"BBB") bitcoin-env `(,zero 1 c) '() '())])
        (check-equal? stack `(,zero c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_numequal '(#"AAA" #"BBB") bitcoin-env '(a 1 c) '() '())])
        (check-equal? stack `(,zero c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_numequal '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_numequalverify '(#"AAA" #"BBB") bitcoin-env '(10 10 c) '() '())])
        (check-equal? stack '(c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_numequalverify '(#"AAA" #"BBB") bitcoin-env `(,zero 1 c) '() '())])
        (check-equal? stack '(c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #f))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_numequalverify '(#"AAA" #"BBB") bitcoin-env '(a 1 c) '() '())])
        (check-equal? stack '(c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #f))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_numequalverify '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_numnotequal '(#"AAA" #"BBB") bitcoin-env '(10 10 c) '() '())])
        (check-equal? stack `(,zero c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_numnotequal '(#"AAA" #"BBB") bitcoin-env `(,zero 1 c) '() '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_numnotequal '(#"AAA" #"BBB") bitcoin-env '(a 1 c) '() '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_numnotequal '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_lessthan '(#"AAA" #"BBB") bitcoin-env '(20 10 c) '() '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_lessthan '(#"AAA" #"BBB") bitcoin-env '(10 20 c) '() '())])
        (check-equal? stack `(,zero c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_lessthan '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_greaterthan '(#"AAA" #"BBB") bitcoin-env '(10 20 c) '() '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_greaterthan '(#"AAA" #"BBB") bitcoin-env '(20 10 c) '() '())])
        (check-equal? stack `(,zero c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_greaterthan '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_lessthanorequal '(#"AAA" #"BBB") bitcoin-env '(20 10 c) '() '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_lessthanorequal '(#"AAA" #"BBB") bitcoin-env '(20 20 c) '() '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_lessthanorequal '(#"AAA" #"BBB") bitcoin-env '(10 20 c) '() '())])
        (check-equal? stack `(,zero c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_lessthanorequal '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_greaterthanorequal '(#"AAA" #"BBB") bitcoin-env '(10 20 c) '() '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_greaterthanorequal '(#"AAA" #"BBB") bitcoin-env '(20 20 c) '() '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_greaterthanorequal '(#"AAA" #"BBB") bitcoin-env '(20 10 c) '() '())])
        (check-equal? stack `(,zero c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_greaterthanorequal '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_min '(#"AAA" #"BBB") bitcoin-env '(20 10 c) '() '())])
        (check-equal? stack '(10 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_min '(#"AAA" #"BBB") bitcoin-env '(10 20 c) '() '())])
        (check-equal? stack '(10 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_min '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_max '(#"AAA" #"BBB") bitcoin-env '(20 10 c) '() '())])
        (check-equal? stack '(20 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_max '(#"AAA" #"BBB") bitcoin-env '(10 20 c) '() '())])
        (check-equal? stack '(20 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_max '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_within '(#"AAA" #"BBB") bitcoin-env '(100 10 50 c) '() '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_within '(#"AAA" #"BBB") bitcoin-env '(100 10 5 c) '() '())])
        (check-equal? stack `(,zero c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_within '(#"AAA" #"BBB") bitcoin-env '(100 10 101 c) '() '())])
        (check-equal? stack `(,zero c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_within '(#"AAA" #"BBB") bitcoin-env '(100 10 100 c) '() '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_within '(#"AAA" #"BBB") bitcoin-env '(100 10 10 c) '() '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_within '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      ))

  (test-case
      "test bitcoin crypto opcodes in bitcoin-environment"
    (let ([bitcoin-env (make-bitcoin-environment)])
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_ripemd160 '(#"AAA" #"BBB") bitcoin-env '(#"abcd" 10 10 c) '() '())])
        (check-equal? stack (list (ripemd160 #"abcd") 10 10 'c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_ripemd160 '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_sha1 '(#"AAA" #"BBB") bitcoin-env '(#"abcd" 10 10 c) '() '())])
        (check-equal? stack (list (sha1 #"abcd") 10 10 'c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_sha1 '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_sha256 '(#"AAA" #"BBB") bitcoin-env '(#"abcd" 10 10 c) '() '())])
        (check-equal? stack (list (sha256 #"abcd") 10 10 'c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_sha256 '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_hash160 '(#"AAA" #"BBB") bitcoin-env '(#"abcd" 10 10 c) '() '())])
        (check-equal? stack (list (hash160 #"abcd") 10 10 'c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_hash160 '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_hash256 '(#"AAA" #"BBB") bitcoin-env '(#"abcd" 10 10 c) '() '())])
        (check-equal? stack (list (double-sha256-hash #"abcd") 10 10 'c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_hash256 '(#"AAA" #"BBB") bitcoin-env '() '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack condstack verified) (apply-opcode 'op_codeseparator '(#"AAA" #"BBB") bitcoin-env '(a b) '() '())])
        (check-equal? stack '(a b))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let*-values ([(test-input) (make-input #:script '() #:witness '() #:sequence 0 #:prevout '())]
                    [(script stack altstack condstack verified)
                     (apply-opcode 'op_checklocktimeverify '(#"AAA" #"BBB") bitcoin-env `(,zero) '() '()
                                   (make-transaction #:version-number 0 #:flag 0 #:inputs (list test-input) #:outputs '() #:lock-time 0) 0)])
        (check-equal? verified #f))
      (let*-values ([(test-input) (make-input #:script '() #:witness '() #:sequence 0 #:prevout '())]
                    [(script stack altstack condstack verified)
                     (apply-opcode 'op_checklocktimeverify '(#"AAA" #"BBB") bitcoin-env '(-1) '() '()
                                   (make-transaction #:version-number 0 #:flag 0 #:inputs (list test-input) #:outputs '() #:lock-time 0) 0)])
        (check-equal? verified #f))
      (let*-values ([(test-input) (make-input #:script '() #:witness '() #:sequence 0 #:prevout '())]
                    [(script stack altstack condstack verified)
                     (apply-opcode 'op_checklocktimeverify '(#"AAA" #"BBB") bitcoin-env '() '() '()
                                   (make-transaction #:version-number 0 #:flag 0 #:inputs (list test-input) #:outputs '() #:lock-time 0) 0)])
        (check-equal? verified #f))
      (let*-values ([(test-input) (make-input #:script '() #:witness '() #:sequence #xffffffff #:prevout '())]
                    [(script stack altstack condstack verified)
                     (apply-opcode 'op_checklocktimeverify '(#"AAA" #"BBB") bitcoin-env '(0) '() '()
                                   (make-transaction #:version-number 0 #:flag 0 #:inputs (list test-input) #:outputs '() #:lock-time 0) 0)])
        (check-equal? verified #f))
      (let*-values ([(test-input) (make-input #:script '() #:witness '() #:sequence 0 #:prevout '())]
                    [(script stack altstack condstack verified)
                     (apply-opcode 'op_checklocktimeverify '(#"AAA" #"BBB") bitcoin-env '(100) '() '()
                                   (make-transaction #:version-number 0 #:flag 0 #:inputs (list test-input) #:outputs '() #:lock-time 50) 0)])
        (check-equal? verified #f))
      (let*-values ([(test-input) (make-input #:script '() #:witness '() #:sequence 0 #:prevout '())]
                    [(script stack altstack condstack verified)
                     (apply-opcode 'op_checklocktimeverify '(#"AAA" #"BBB") bitcoin-env '(100) '() '()
                                   (make-transaction #:version-number 0 #:flag 0 #:inputs (list test-input) #:outputs '() #:lock-time 101) 0)])
        (check-equal? verified #t))
      (let*-values ([(test-input) (make-input #:script '() #:witness '() #:sequence 0 #:prevout '())]
                    [(script stack altstack condstack verified)
                     (apply-opcode 'op_checklocktimeverify '(#"AAA" #"BBB") bitcoin-env '(100) '() '()
                                   (make-transaction #:version-number 0 #:flag 0 #:inputs (list test-input) #:outputs '() #:lock-time 500000001) 0)])
        (check-equal? verified #f))
      (let*-values ([(test-input) (make-input #:script '() #:witness '() #:sequence 0 #:prevout '())]
                    [(script stack altstack condstack verified)
                     (apply-opcode 'op_checklocktimeverify '(#"AAA" #"BBB") bitcoin-env '(500000001) '() '()
                                   (make-transaction #:version-number 0 #:flag 0 #:inputs (list test-input) #:outputs '() #:lock-time 100) 0)])
        (check-equal? verified #f))

      (let*-values ([(test-input) (make-input #:script '() #:witness '() #:sequence 0 #:prevout '())]
                    [(script stack altstack condstack verified)
                     (apply-opcode 'op_checksequenceverify '(#"AAA" #"BBB") bitcoin-env '() '() '()
                                   (make-transaction #:version-number 0 #:flag 0 #:inputs (list test-input) #:outputs '() #:lock-time 0) 0)])
        (check-equal? verified #f))
      (let*-values ([(test-input) (make-input #:script '() #:witness '() #:sequence 0 #:prevout '())]
                    [(script stack altstack condstack verified)
                     (apply-opcode 'op_checksequenceverify '(#"AAA" #"BBB") bitcoin-env '(-1) '() '()
                                   (make-transaction #:version-number 0 #:flag 0 #:inputs (list test-input) #:outputs '() #:lock-time 0) 0)])
        (check-equal? verified #f))
      (let*-values ([(test-input) (make-input #:script '() #:witness '() #:sequence 0 #:prevout '())]
                    [(script stack altstack condstack verified)
                     (apply-opcode 'op_checksequenceverify '(#"AAA" #"BBB") bitcoin-env '(100) '() '()
                                   (make-transaction #:version-number 0 #:flag 0 #:inputs (list test-input) #:outputs '() #:lock-time 0) 0)])
        (check-equal? verified #f))
      (let*-values ([(test-input) (make-input #:script '() #:witness '() #:sequence 2147483649 #:prevout '())]
                    [(script stack altstack condstack verified)
                     (apply-opcode 'op_checksequenceverify '(#"AAA" #"BBB") bitcoin-env '(100) '() '()
                                   (make-transaction #:version-number 2 #:flag 0 #:inputs (list test-input) #:outputs '() #:lock-time 0) 0)])
        (check-equal? verified #f))
      (let*-values ([(test-input) (make-input #:script '() #:witness '() #:sequence 100 #:prevout '())]
                    [(script stack altstack condstack verified)
                     (apply-opcode 'op_checksequenceverify '(#"AAA" #"BBB") bitcoin-env '(4194305) '() '()
                                   (make-transaction #:version-number 2 #:flag 0 #:inputs (list test-input) #:outputs '() #:lock-time 0) 0)])
        (check-equal? verified #f))
      (let*-values ([(test-input) (make-input #:script '() #:witness '() #:sequence 4194305 #:prevout '())]
                    [(script stack altstack condstack verified)
                     (apply-opcode 'op_checksequenceverify '(#"AAA" #"BBB") bitcoin-env '(100) '() '()
                                   (make-transaction #:version-number 2 #:flag 0 #:inputs (list test-input) #:outputs '() #:lock-time 0) 0)])
        (check-equal? verified #f))
      (let*-values ([(test-input) (make-input #:script '() #:witness '() #:sequence 100 #:prevout '())]
                    [(script stack altstack condstack verified)
                     (apply-opcode 'op_checksequenceverify '(#"AAA" #"BBB") bitcoin-env '(4194305) '() '()
                                   (make-transaction #:version-number 2 #:flag 0 #:inputs (list test-input) #:outputs '() #:lock-time 0) 0)])
        (check-equal? verified #f))
      (let*-values ([(test-input) (make-input #:script '() #:witness '() #:sequence 100 #:prevout '())]
                    [(script stack altstack condstack verified)
                     (apply-opcode 'op_checksequenceverify '(#"AAA" #"BBB") bitcoin-env '(99) '() '()
                                   (make-transaction #:version-number 2 #:flag 0 #:inputs (list test-input) #:outputs '() #:lock-time 0) 0)])
        (check-equal? verified #f))
      (let*-values ([(test-input) (make-input #:script '() #:witness '() #:sequence 100 #:prevout '())]
                    [(script stack altstack condstack verified)
                     (apply-opcode 'op_checksequenceverify '(#"AAA" #"BBB") bitcoin-env '(101) '() '()
                                   (make-transaction #:version-number 2 #:flag 0 #:inputs (list test-input) #:outputs '() #:lock-time 0) 0)])
        (check-equal? verified #t))
      ))
      
  (test-case
      "test eval-script in bitcoin-environment"
    (let ([bitcoin-env (make-bitcoin-environment)])
      (let-values ([(script stack altstack condstack verified)
                    (eval-script '(op_if #x4c 2 #"AA" #x4c 3 #"AAA" op_else #x4c 2 #"BB" #x4c 3 #"BBB" op_endif) bitcoin-env `(,zero blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"BBB" #"BB" blah)))
      (let-values ([(script stack altstack condstack verified)
                    (eval-script '(op_if #x4c 2 #"AA" #x4c 3 #"AAA" op_else #x4c 2 #"BB" #x4c 3 #"BBB" op_endif #x4c 3 #"CCC") bitcoin-env `(,zero blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"CCC" #"BBB" #"BB" blah)))
      (let-values ([(script stack altstack condstack verified)
                    (eval-script '(op_if #x4c 2 #"AA" #x4c 3 #"AAA" op_else #x4c 2 #"BB" #x4c 3 #"BBB" op_endif) bitcoin-env '(1 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"AAA" #"AA" blah)))
      (let-values ([(script stack altstack condstack verified)
                    (eval-script '(op_notif #x4c 2 #"AA" #x4c 3 #"AAA" op_else #x4c 2 #"BB" #x4c 3 #"BBB" op_endif) bitcoin-env '(1 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"BBB" #"BB" blah)))
      (let-values ([(script stack altstack condstack verified)
                    (eval-script '(op_notif #x4c 2 #"AA" #x4c 3 #"AAA" op_else #x4c 2 #"BB" #x4c 3 #"BBB" op_endif) bitcoin-env `(,zero blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"AAA" #"AA" blah)))
      (let-values ([(script stack altstack condstack verified)
                    (eval-script '(op_if #x4c 2 #"AA" #x4c 3 #"AAA" op_endif) bitcoin-env '(1 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"AAA" #"AA" blah)))
      (let-values ([(script stack altstack condstack verified)
                    (eval-script '(op_if #x4c 2 #"AA" #x4c 3 #"AAA" op_endif op_10) bitcoin-env '(1 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(10  #"AAA" #"AA" blah)))
      ;; (let-values ([(script stack altstack condstack verified)
      ;;               (eval-script '(op_if 0 op_if 2 op_else 3 op_endif op_endif op_10) bitcoin-env '(1) '())])
      ;;   (check-equal? script '())
      ;;   (check-equal? stack '(10  3)))
      (let-values ([(script stack altstack condstack verified)
                    (eval-script '(op_if #x4c 2 #"AA" #x4c 3 #"AAA" op_endif) bitcoin-env `(,zero blah) '())])
        (check-equal? script '())
        (check-equal? stack '(blah)))
      )))
