#lang errortrace racket/base

(require "environment.rkt"
         "bitcoin-environment.rkt"
         "eval-script.rkt"
         "../../crypto-utils.rkt")

(module+ test
  (require rackunit))


(module+ test
  (test-case
      "smoke test for making bitcoin environment"
    (let ([bitcoin-env (make-bitcoin-environment)])
      (check-not-eq? bitcoin-env '())
      (check-true (is-opcode? #x00 bitcoin-env))
      (check-true (is-opcode? #x01 bitcoin-env))
      )))

(module+ test
  (test-case
      "test bitcoin opcodes in bitcoin-environment"
    (let ([bitcoin-env (make-bitcoin-environment)])
      (let-values ([(script stack altstack verified) (apply-opcode 'op_false '() bitcoin-env '() '())])
        (check-equal? stack '(0)))
      (let-values ([(script stack altstack verified) (apply-opcode #x01 '(#"A") bitcoin-env '() '())])
        (check-equal? script '())
        (check-equal? stack  '(#"A")))
      (let-values ([(script stack altstack verified) (apply-opcode #x02 '(#"BC") bitcoin-env '() '())])
        (check-equal? script '())
        (check-equal? stack  '(#"BC")))
      (let-values ([(script stack altstack verified) (apply-opcode #x4c '(#x02 #"BC") bitcoin-env '() '())])
        (check-equal? script '())
        (check-equal? stack '(#"BC")))
      (let-values ([(script stack altstack verified) (apply-opcode #x4d '(#x0002 #"BC") bitcoin-env '() '())])
        (check-equal? script '())
        (check-equal? stack '(#"BC")))
      (let-values ([(script stack altstack verified) (apply-opcode #x4e '(#x000002 #"BC") bitcoin-env '() '())])
        (check-equal? script '())
        (check-equal? stack '(#"BC")))
      (let-values ([(script stack altstack verified) (apply-opcode #x4f '() bitcoin-env '(blah) '())])
        (check-equal? script '())
        (check-equal? stack '(-1 blah)))
      (let-values ([(script stack altstack verified) (apply-opcode #x51 '() bitcoin-env '(blah) '())])
        (check-equal? script '())
        (check-equal? stack '(1 blah)))
      (let-values ([(script stack altstack verified) (apply-opcode #x52 '() bitcoin-env '(blah) '())])
        (check-equal? script '())
        (check-equal? stack '(2 blah)))
      (let-values ([(script stack altstack verified) (apply-opcode #x60 '() bitcoin-env '(blah) '())])
        (check-equal? script '())
        (check-equal? stack '(16 blah)))
      (let-values ([(script stack altstack verified) (apply-opcode #x61 '() bitcoin-env '(blah) '())])
        (check-equal? script '())
        (check-equal? stack '(blah)))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_if '((2 #"AA" 3 #"AAA") op_endif) bitcoin-env '(1 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"AAA" #"AA" blah)))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_if '((2 #"AA" 3 #"AAA") op_endif) bitcoin-env '(0 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(blah)))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_if '((2 #"AA" 3 #"AAA") op_else (2 #"BB" 3 #"BBB") op_endif) bitcoin-env '(1 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"AAA" #"AA" blah)))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_if '((2 #"AA" 3 #"AAA") op_else (2 #"BB" 3 #"BBB") op_endif) bitcoin-env '(0 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"BBB" #"BB" blah)))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_notif '((2 #"AA" 3 #"AAA") op_endif) bitcoin-env '(0 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"AAA" #"AA" blah)))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_notif '((2 #"AA" 3 #"AAA") op_endif) bitcoin-env '(1 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(blah)))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_notif '((2 #"AA" 3 #"AAA") op_else (2 #"BB" 3 #"BBB") op_endif) bitcoin-env '(0 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"AAA" #"AA" blah)))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_notif '((2 #"AA" 3 #"AAA") op_else (2 #"BB" 3 #"BBB") op_endif) bitcoin-env '(1 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"BBB" #"BB" blah)))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_if '((op_if (2 #"ZZ") op_endif) op_else (2 #"BB" 3 #"BBB") op_endif) bitcoin-env '(1 1 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"ZZ" blah)))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_verify '() bitcoin-env '(0) '())])
          (check-equal? verified #f))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_return '(#"AAA" #"BBB") bitcoin-env '(0) '())])
        (check-equal? stack '(0))
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #f))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_toaltstack '(#"AAA" #"BBB") bitcoin-env '(0) '())])
        (check-equal? stack '())
        (check-equal? altstack '(0))
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_fromaltstack '(#"AAA" #"BBB") bitcoin-env '(0) '(1))])
        (check-equal? stack '(1 0))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_ifdup '(#"AAA" #"BBB") bitcoin-env '(1) '())])
        (check-equal? stack '(1 1))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_ifdup '(#"AAA" #"BBB") bitcoin-env '(0 1) '())])
        (check-equal? stack '(0 1))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_depth '(#"AAA" #"BBB") bitcoin-env '(0 1) '())])
        (check-equal? stack '(2 0 1))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_drop '(#"AAA" #"BBB") bitcoin-env '(0 1) '())])
        (check-equal? stack '(1))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_drop '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_dup '(#"AAA" #"BBB") bitcoin-env '(0 1) '())])
        (check-equal? stack '(0 0 1))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_dup '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_nip '(#"AAA" #"BBB") bitcoin-env '(0 1) '())])
        (check-equal? stack '(0))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_nip '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_over '(#"AAA" #"BBB") bitcoin-env '(0 1 2 3) '())])
        (check-equal? stack '(1 0 2 3))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_over '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_pick '(#"AAA" #"BBB") bitcoin-env '(3 a b c d) '())])
        (check-equal? stack '(d a b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_pick '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_roll '(#"AAA" #"BBB") bitcoin-env '(2 a b c d) '())])
        (check-equal? stack '(c a b d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_roll '(#"AAA" #"BBB") bitcoin-env '(0 a b c d) '())])
        (check-equal? stack '(a b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_roll '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_rot '(#"AAA" #"BBB") bitcoin-env '(a b c d) '())])
        (check-equal? stack '(d a b c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_rot '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_swap '(#"AAA" #"BBB") bitcoin-env '(a b c d) '())])
        (check-equal? stack '(b a c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_swap '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_tuck '(#"AAA" #"BBB") bitcoin-env '(a b c d) '())])
        (check-equal? stack '(a b a c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_tuck '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_2drop '(#"AAA" #"BBB") bitcoin-env '(a b c d) '())])
        (check-equal? stack '(c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_2drop '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_2dup '(#"AAA" #"BBB") bitcoin-env '(a b c d) '())])
        (check-equal? stack '(a b a b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_2dup '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_3dup '(#"AAA" #"BBB") bitcoin-env '(a b c d) '())])
        (check-equal? stack '(a b c a b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_3dup '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_2over '(#"AAA" #"BBB") bitcoin-env '(a b c d) '())])
        (check-equal? stack '(c d a b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_2over '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_2rot '(#"AAA" #"BBB") bitcoin-env '(a b c d e f g h) '())])
        (check-equal? stack '(e f a b c d g h))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_2rot '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_2swap '(#"AAA" #"BBB") bitcoin-env '(a b c d e f g h) '())])
        (check-equal? stack '(c d a b e f g h))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_2swap '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_size '(#"AAA" #"BBB") bitcoin-env '("abcd" x) '())])
        (check-equal? stack '(4 "abcd" x))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_size '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_equal '(#"AAA" #"BBB") bitcoin-env '(a a b c d) '())])
        (check-equal? stack '(#t b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_equal '(#"AAA" #"BBB") bitcoin-env '(a e b c d) '())])
        (check-equal? stack '(#f b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_equal '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_equalverify '(#"AAA" #"BBB") bitcoin-env '(a a b c d) '())])
        (check-equal? stack '(b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_equalverify '(#"AAA" #"BBB") bitcoin-env '(a e b c d) '())])
        (check-equal? stack '(b c d))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #f))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_equalverify '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #f))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_1add '(#"AAA" #"BBB") bitcoin-env '(10 100) '())])
        (check-equal? stack '(11 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_1add '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_1sub '(#"AAA" #"BBB") bitcoin-env '(10 100) '())])
        (check-equal? stack '(9 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_1sub '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_negate '(#"AAA" #"BBB") bitcoin-env '(10 100) '())])
        (check-equal? stack '(-10 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_negate '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_abs '(#"AAA" #"BBB") bitcoin-env '(-10 100) '())])
        (check-equal? stack '(10 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_abs '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_not '(#"AAA" #"BBB") bitcoin-env '(0 100) '())])
        (check-equal? stack '(1 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_not '(#"AAA" #"BBB") bitcoin-env '(1 100) '())])
        (check-equal? stack '(0 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_not '(#"AAA" #"BBB") bitcoin-env '(a 100) '())])
        (check-equal? stack '(0 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_not '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_0notequal '(#"AAA" #"BBB") bitcoin-env '(0 100) '())])
        (check-equal? stack '(0 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_0notequal '(#"AAA" #"BBB") bitcoin-env '(1 100) '())])
        (check-equal? stack '(1 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_0notequal '(#"AAA" #"BBB") bitcoin-env '(a 100) '())])
        (check-equal? stack '(1 100))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_0notequal '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_add '(#"AAA" #"BBB") bitcoin-env '(1 100) '())])
        (check-equal? stack '(101))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_add '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_sub '(#"AAA" #"BBB") bitcoin-env '(100 10) '())])
        (check-equal? stack '(90))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_sub '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack verified) (apply-opcode 'op_booland '(#"AAA" #"BBB") bitcoin-env '(a b c) '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_booland '(#"AAA" #"BBB") bitcoin-env '(0 0 c) '())])
        (check-equal? stack '(0 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_booland '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack verified) (apply-opcode 'op_boolor '(#"AAA" #"BBB") bitcoin-env '(a 0 c) '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_boolor '(#"AAA" #"BBB") bitcoin-env '(0 0 c) '())])
        (check-equal? stack '(0 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_boolor '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack verified) (apply-opcode 'op_numequal '(#"AAA" #"BBB") bitcoin-env '(10 10 c) '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_numequal '(#"AAA" #"BBB") bitcoin-env '(0 1 c) '())])
        (check-equal? stack '(0 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_numequal '(#"AAA" #"BBB") bitcoin-env '(a 1 c) '())])
        (check-equal? stack '(0 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_numequal '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack verified) (apply-opcode 'op_numequalverify '(#"AAA" #"BBB") bitcoin-env '(10 10 c) '())])
        (check-equal? stack '(c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_numequalverify '(#"AAA" #"BBB") bitcoin-env '(0 1 c) '())])
        (check-equal? stack '(c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #f))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_numequalverify '(#"AAA" #"BBB") bitcoin-env '(a 1 c) '())])
        (check-equal? stack '(c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #f))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_numequalverify '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack verified) (apply-opcode 'op_numnotequal '(#"AAA" #"BBB") bitcoin-env '(10 10 c) '())])
        (check-equal? stack '(0 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_numnotequal '(#"AAA" #"BBB") bitcoin-env '(0 1 c) '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_numnotequal '(#"AAA" #"BBB") bitcoin-env '(a 1 c) '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_numnotequal '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack verified) (apply-opcode 'op_lessthan '(#"AAA" #"BBB") bitcoin-env '(20 10 c) '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_lessthan '(#"AAA" #"BBB") bitcoin-env '(10 20 c) '())])
        (check-equal? stack '(0 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_lessthan '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack verified) (apply-opcode 'op_greaterthan '(#"AAA" #"BBB") bitcoin-env '(10 20 c) '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_greaterthan '(#"AAA" #"BBB") bitcoin-env '(20 10 c) '())])
        (check-equal? stack '(0 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_greaterthan '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack verified) (apply-opcode 'op_lessthanorequal '(#"AAA" #"BBB") bitcoin-env '(20 10 c) '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_lessthanorequal '(#"AAA" #"BBB") bitcoin-env '(20 20 c) '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_lessthanorequal '(#"AAA" #"BBB") bitcoin-env '(10 20 c) '())])
        (check-equal? stack '(0 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_lessthanorequal '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack verified) (apply-opcode 'op_greaterthanorequal '(#"AAA" #"BBB") bitcoin-env '(10 20 c) '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_greaterthanorequal '(#"AAA" #"BBB") bitcoin-env '(20 20 c) '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_greaterthanorequal '(#"AAA" #"BBB") bitcoin-env '(20 10 c) '())])
        (check-equal? stack '(0 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_greaterthanorequal '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack verified) (apply-opcode 'op_min '(#"AAA" #"BBB") bitcoin-env '(20 10 c) '())])
        (check-equal? stack '(10 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_min '(#"AAA" #"BBB") bitcoin-env '(10 20 c) '())])
        (check-equal? stack '(10 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_min '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack verified) (apply-opcode 'op_max '(#"AAA" #"BBB") bitcoin-env '(20 10 c) '())])
        (check-equal? stack '(20 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_max '(#"AAA" #"BBB") bitcoin-env '(10 20 c) '())])
        (check-equal? stack '(20 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_max '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack verified) (apply-opcode 'op_within '(#"AAA" #"BBB") bitcoin-env '(100 10 50 c) '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_within '(#"AAA" #"BBB") bitcoin-env '(100 10 5 c) '())])
        (check-equal? stack '(0 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_within '(#"AAA" #"BBB") bitcoin-env '(100 10 101 c) '())])
        (check-equal? stack '(0 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_within '(#"AAA" #"BBB") bitcoin-env '(100 10 100 c) '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_within '(#"AAA" #"BBB") bitcoin-env '(100 10 10 c) '())])
        (check-equal? stack '(1 c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_within '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      ))

  (test-case
      "test bitcoin crypto opcodes in bitcoin-environment"
    (let ([bitcoin-env (make-bitcoin-environment)])
      (let-values ([(script stack altstack verified) (apply-opcode 'op_ripemd160 '(#"AAA" #"BBB") bitcoin-env '(#"abcd" 10 10 c) '())])
        (check-equal? stack (list (hash160 #"abcd") 10 10 'c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_ripemd160 '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))

      (let-values ([(script stack altstack verified) (apply-opcode 'op_sha1 '(#"AAA" #"BBB") bitcoin-env '(#"abcd" 10 10 c) '())])
        (check-equal? stack (list (sha1 #"abcd") 10 10 'c))
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      (let-values ([(script stack altstack verified) (apply-opcode 'op_sha1 '(#"AAA" #"BBB") bitcoin-env '() '())])
        (check-equal? stack '())
        (check-equal? altstack '())
        (check-equal? script '(#"AAA" #"BBB"))
        (check-equal? verified #t))
      ))
      
  (test-case
      "test eval-script in bitcoin-environment"
    (let ([bitcoin-env (make-bitcoin-environment)])
      (let-values ([(script env stack altstack)
                    (eval-script '(op_if (2 #"AA" 3 #"AAA") op_else (2 #"BB" 3 #"BBB") op_endif) bitcoin-env '(0 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"BBB" #"BB" blah)))
      (let-values ([(script env stack altstack)
                    (eval-script '(op_if (2 #"AA" 3 #"AAA") op_else (2 #"BB" 3 #"BBB") op_endif) bitcoin-env '(1 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"AAA" #"AA" blah)))
      (let-values ([(script env stack altstack)
                    (eval-script '(op_notif (2 #"AA" 3 #"AAA") op_else (2 #"BB" 3 #"BBB") op_endif) bitcoin-env '(1 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"BBB" #"BB" blah)))
      (let-values ([(script env stack altstack)
                    (eval-script '(op_notif (2 #"AA" 3 #"AAA") op_else (2 #"BB" 3 #"BBB") op_endif) bitcoin-env '(0 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"AAA" #"AA" blah)))
      (let-values ([(script env stack altstack)
                    (eval-script '(op_if (2 #"AA" 3 #"AAA") op_endif) bitcoin-env '(1 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(#"AAA" #"AA" blah)))
      (let-values ([(script env stack altstack)
                    (eval-script '(op_if (2 #"AA" 3 #"AAA") op_endif) bitcoin-env '(0 blah) '())])
        (check-equal? script '())
        (check-equal? stack '(blah)))
      )))
